{{- $root := . -}}
{{- range .Values.buckets }}
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: {{ .name }}
spec:
  cluster: {{ $root.Values.clusterName | default "couchbase-cluster" | quote }}
  memoryQuota: {{ .memory | quote }}
  ioPriority: {{ default "low" .ioPriority | quote }}
  {{- if .storageBackend }}
  storageBackend: {{ .storageBackend | quote }}
  {{- end }}
  {{- if .evictionPolicy }}
  evictionPolicy: {{ .evictionPolicy | quote }}
  {{- end }}
  replicas: 1
  conflictResolution: seqno
---
{{- end }}
