{{- range .Values.buckets }}
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: {{ .name }}
spec:
  memoryQuota: {{ .memory | quote }}
  ioPriority: {{ default "low" .ioPriority | quote }}
  replicas: 1
  conflictResolution: seqno
---
{{- end }}

