extends: default

rules:
  # Many Helm-maintained YAML files (Chart.yaml, values.yaml, tests) intentionally
  # omit the leading document marker. Treat missing '---' as acceptable.
  document-start: disable

  # Keep defaults for other rules; adjust incrementally if needed.
