enabled: true

# Controls whether a ClusterSecretStore is rendered.
# Disable if you already manage the store out-of-band.
secretStore:
  enabled: true
  name: vault-global
  provider:
    vault:
      server: https://vault.example.com
      # Path to the Vault namespace (Enterprise) or leave empty for OSS.
      namespace: ""
      path: secret
      version: v2
      auth:
        method: kubernetes
        mount: kubernetes
        role: gitops-prod
        serviceAccountRef:
          name: vault-auth
          namespace: openshift-gitops

# ExternalSecret definitions. Each block can still be toggled, but defaults to enabled.
argocdToken:
  enabled: true
  targetSecretName: argocd-image-updater-secret
  targetNamespace: openshift-gitops
  refreshInterval: 1m
  data:
    - secretKey: argocd.token
      remoteRef:
        key: gitops/data/argocd/image-updater
        property: token
  # Optional annotations for the generated Secret
  annotations: {}

quayCredentials:
  enabled: true
  targetSecretName: quay-auth
  targetNamespace: openshift-pipelines
  refreshInterval: 5m
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: gitops/data/registry/quay
        property: dockerconfigjson
  secretType: kubernetes.io/dockerconfigjson
  # Optional annotations for the generated Secret (e.g., Tekton credential helper)
  # annotations:
  #   tekton.dev/docker-0: https://quay.io
  annotations: {}

webhookSecret:
  enabled: true
  targetSecretName: github-webhook-secret
  targetNamespace: openshift-pipelines
  refreshInterval: 1m
  data:
    - secretKey: secretToken
      remoteRef:
        key: gitops/data/github/webhook
        property: token
  # Optional annotations for the generated Secret
  annotations: {}

toyServiceConfig:
  enabled: true
  targetSecretName: toy-service-config
  targetNamespace: bitiq-local
  refreshInterval: 1m
  data:
    - secretKey: FAKE_SECRET
      remoteRef:
        key: gitops/data/services/toy-service/config
        property: fake_secret
  # Optional annotations for the generated Secret
  annotations: {}

toyWebConfig:
  enabled: true
  targetSecretName: toy-web-config
  targetNamespace: bitiq-local
  refreshInterval: 1m
  data:
    - secretKey: API_BASE_URL
      remoteRef:
        key: gitops/data/services/toy-web/config
        property: api_base_url
  # Optional annotations for the generated Secret
  annotations: {}

updaterPullSecret:
  enabled: true
  targetSecretName: quay-creds
  targetNamespace: openshift-gitops
  refreshInterval: 5m
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: gitops/data/registry/quay
        property: dockerconfigjson
  secretType: kubernetes.io/dockerconfigjson
  annotations: {}

# Common fields applied to ExternalSecret resources.
externalSecretDefaults:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-global
  creationPolicy: Owner
