{{- if .Values.enabled }}
{{- $cf := .Values.secrets.cloudflareApiToken -}}
{{- if $cf.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $cf.destinationName }}
  namespace: {{ $cf.namespace | default "cert-manager" }}
spec:
  mount: gitops
  type: kv-v2
  path: {{ $cf.path }}
  destination:
    create: true
    overwrite: true
    name: {{ $cf.destinationName }}
    type: {{ $cf.type | default "Opaque" }}
  vaultAuthRef: k8s
{{- end }}
{{- $r53 := .Values.secrets.route53Credentials -}}
{{- if $r53.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $r53.destinationName }}
  namespace: {{ $r53.namespace | default "cert-manager" }}
spec:
  mount: gitops
  type: kv-v2
  path: {{ $r53.path }}
  destination:
    create: true
    overwrite: true
    name: {{ $r53.destinationName }}
    type: {{ $r53.type | default "Opaque" }}
  vaultAuthRef: k8s
{{- end }}
{{- end }}
