replicaCount: 1

image:
  repository: ghcr.io/traefik/whoami
  tag: "v1.10.2"
  pullPolicy: IfNotPresent

service:
  port: 80
  type: ClusterIP

# Will be set per-env; used to build Route host
baseDomain: ""
hostPrefix: "svc-api"

healthPath: "/"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
