baseDomain: ""

backend:
  replicaCount: 1
  hostPrefix: "svc-api"
  healthPath: "/"
  image:
    repository: quay.io/paulcapestany/toy-service
    tag: "v0.2.21-commit.b7791f1"
    pullPolicy: IfNotPresent
  service:
    port: 8080
    type: ClusterIP
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

frontend:
  enabled: true
  replicaCount: 1
  hostPrefix: "svc-web"
  healthPath: "/"
  image:
    repository: quay.io/paulcapestany/toy-web
    tag: "v0.0.0-commit.0000000"
    pullPolicy: IfNotPresent
  service:
    port: 8080
    type: ClusterIP
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
