baseDomain: apps-crc.testing
backend:
  healthPath: "/healthz"
  image:
    repository: quay.io/paulcapestany/toy-service
    tag: v0.3.19-commit.fcedae7
frontend:
  image:
    repository: quay.io/paulcapestany/toy-web
    tag: v0.1.19-commit.a573ab4
