apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
  namespace: {{ .Values.argoNamespace }}
  labels:
    app.kubernetes.io/name: argocd-image-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-image-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-image-updater
    spec:
      serviceAccountName: argocd-image-updater
      securityContext:
        runAsNonRoot: true
      containers:
        - name: argocd-image-updater
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          args:
            - run
            - --loglevel={{ .Values.logLevel }}
            - --argocd-server={{ .Values.argocd.server }}:{{ .Values.argocd.port }}
            {{- if .Values.argocd.insecure }}
            - --argocd-insecure
            {{- end }}
          env:
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.key }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
