apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
  namespace: {{ .Values.argoNamespace }}
  labels:
    app.kubernetes.io/name: argocd-image-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-image-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-image-updater
    spec:
      serviceAccountName: argocd-image-updater
      containers:
        - name: argocd-image-updater
          image: quay.io/argoprojlabs/argocd-image-updater:latest
          args:
            - --log-level={{ .Values.logLevel }}
            - --applications-namespace={{ .Values.applicationNamespaces }}
            - --argocd-server={{ .Values.argocd.server }}:{{ .Values.argocd.port }}
            {{- if .Values.argocd.insecure }}
            - --argocd-insecure
            {{- end }}
          env:
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-image-updater-secret
                  key: argocd.token