apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-image-updater
  namespace: {{ .Values.argoNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-image-updater
  namespace: {{ .Values.argoNamespace }}
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-image-updater
  namespace: {{ .Values.argoNamespace }}
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: argocd-image-updater