---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-sites-pvc
  namespace: bitiq-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.5Gi
  # Use cluster default StorageClass for CRC/local
