apiVersion: v1
kind: Service
metadata:
  name: toy-service
  labels:
    app.kubernetes.io/name: toy-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: toy-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
