{{- $cm := default (dict) .Values.certManager }}
{{- $cmEnabled := false }}
{{- if hasKey $cm "enabled" }}
  {{- $cmEnabled = eq (lower (printf "%v" (get $cm "enabled"))) "true" }}
{{- end }}
{{- if $cmEnabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config-{{ .Values.env }}
  namespace: {{ .Values.gitopsNamespace }}
  labels:
    bitiq.io/env: {{ .Values.env }}
    app.kubernetes.io/part-of: bitiq-umbrella
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    targetRevision: {{ .Values.targetRevision }}
    path: charts/cert-manager-config
    helm:
      valueFiles:
        - values-common.yaml
        - values-{{ .Values.env }}.yaml
      ignoreMissingValueFiles: true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.gitopsNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
    syncOptions:
      - CreateNamespace=true
{{- end }}

