apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-pipelines-{{ .Values.env }}
  namespace: {{ .Values.gitopsNamespace }}
  labels:
    bitiq.io/env: {{ .Values.env }}
    app.kubernetes.io/part-of: bitiq-umbrella
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    targetRevision: {{ .Values.targetRevision }}
    path: charts/ci-pipelines
    helm:
      parameters:
        - name: env
          value: {{ .Values.env | quote }}
        - name: appNamespace
          value: {{ .Values.appNamespace | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.pipelinesNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
