{{- if eq (include "ollama.mode" .) "gpu" }}
{{- $persistence := .Values.gpu.persistence }}
{{- $volumeMountBag := dict "items" (list) }}
{{- if and $persistence.enabled $persistence.mountPath }}
  {{- $vmItem := dict "name" "ollama-models" "mountPath" $persistence.mountPath }}
  {{- $_ := set $volumeMountBag "items" (append (index $volumeMountBag "items") $vmItem) }}
{{- end }}
{{- range $extra := .Values.gpu.extraVolumeMounts }}
  {{- $_ := set $volumeMountBag "items" (append (index $volumeMountBag "items") $extra) }}
{{- end }}
{{- $volumesBag := dict "items" (list) }}
{{- if and $persistence.enabled (not $persistence.existingClaim) }}
  {{- $pvc := dict "name" "ollama-models" "persistentVolumeClaim" (dict "claimName" "ollama-models") }}
  {{- $_ := set $volumesBag "items" (append (index $volumesBag "items") $pvc) }}
{{- else if and $persistence.enabled $persistence.existingClaim }}
  {{- $pvc := dict "name" "ollama-models" "persistentVolumeClaim" (dict "claimName" $persistence.existingClaim) }}
  {{- $_ := set $volumesBag "items" (append (index $volumesBag "items") $pvc) }}
{{- end }}
{{- range $extraVolume := .Values.gpu.extraVolumes }}
  {{- $_ := set $volumesBag "items" (append (index $volumesBag "items") $extraVolume) }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
{{ include "ollama.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.gpu.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.gpu.podLabels }}
{{ toYaml . | indent 8 }}
        {{- end }}
      {{- with .Values.gpu.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- if .Values.gpu.runtimeClassName }}
      runtimeClassName: {{ .Values.gpu.runtimeClassName | quote }}
      {{- end }}
      {{- with .Values.gpu.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- $saName := .Values.gpu.serviceAccount.name }}
      {{- if and .Values.gpu.serviceAccount.create (not $saName) }}
      serviceAccountName: ollama
      {{- else if $saName }}
      serviceAccountName: {{ $saName }}
      {{- end }}
      {{- with .Values.gpu.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.gpu.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.gpu.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: ollama
          image: {{ .Values.gpu.image.repository }}:{{ .Values.gpu.image.tag }}
          imagePullPolicy: {{ .Values.gpu.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.gpu.service.port }}
          {{- with .Values.gpu.env }}
          env:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.gpu.envFrom }}
          envFrom:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.gpu.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.gpu.resources }}
          resources:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.gpu.startupProbe }}
          startupProbe:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.gpu.readinessProbe }}
          readinessProbe:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.gpu.livenessProbe }}
          livenessProbe:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- if (gt (len (index $volumeMountBag "items")) 0) }}
          volumeMounts:
{{ toYaml (index $volumeMountBag "items") | indent 12 }}
          {{- end }}
      {{- if (gt (len (index $volumesBag "items")) 0) }}
      volumes:
{{ toYaml (index $volumesBag "items") | indent 8 }}
      {{- end }}
{{- end }}
