{{- if eq (include "ollama.mode" .) "gpu" }}
{{- $persistence := .Values.gpu.persistence }}
{{- if and $persistence.enabled (not $persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  labels:
{{ include "ollama.labels" . | indent 4 }}
spec:
  accessModes:
{{ toYaml $persistence.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ $persistence.size | default "100Gi" }}
  {{- if $persistence.storageClassName }}
  storageClassName: {{ $persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
{{- end }}
