{{- if eq (include "ollama.mode" .) "gpu" }}
{{- if and .Values.gpu.serviceAccount.create (not .Values.gpu.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama
  labels:
{{ include "ollama.labels" . | indent 4 }}
{{- end }}
{{- end }}
