apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitiq-sample-app
  labels:
    app.kubernetes.io/name: bitiq-sample-app
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: bitiq-sample-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitiq-sample-app
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          args:
            - "--port"
            - "{{ .Values.backend.service.port }}"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.healthPath | default "/healthz" }}
              port: http
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.healthPath | default "/healthz" }}
              port: http
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
