{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitiq-sample-app-web
  labels:
    app.kubernetes.io/name: bitiq-sample-app-web
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: bitiq-sample-app-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitiq-sample-app-web
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.healthPath | default "/" }}
              port: http
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.healthPath | default "/" }}
              port: http
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
