{{- if and .Values.enabled .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name | quote }}
spec:
  provider:
    vault:
      server: {{ .Values.secretStore.provider.vault.server | quote }}
      {{- with .Values.secretStore.provider.vault.namespace }}
      namespace: {{ . | quote }}
      {{- end }}
      path: {{ .Values.secretStore.provider.vault.path | default "secret" | quote }}
      version: {{ .Values.secretStore.provider.vault.version | default "v2" | quote }}
      auth:
        {{- $auth := .Values.secretStore.provider.vault.auth -}}
        {{- $method := lower ($auth.method | default "kubernetes") -}}
        {{- if eq $method "kubernetes" }}
        kubernetes:
          mountPath: {{ $auth.mount | default "kubernetes" | quote }}
          role: {{ required "Set secretStore.provider.vault.auth.role when using kubernetes auth" $auth.role | quote }}
          serviceAccountRef:
            name: {{ required "Set serviceAccountRef.name for kubernetes auth" $auth.serviceAccountRef.name | quote }}
            namespace: {{ required "Set serviceAccountRef.namespace for kubernetes auth" $auth.serviceAccountRef.namespace | quote }}
        {{- else if eq $method "approle" }}
        appRole:
          path: {{ $auth.mount | default "approle" | quote }}
          roleId: {{ required "Set secretStore.provider.vault.auth.roleId when using approle auth" $auth.roleId | quote }}
          secretRef:
            name: {{ required "Set secretStore.provider.vault.auth.secretRef.name when using approle auth" $auth.secretRef.name | quote }}
            namespace: {{ required "Set secretStore.provider.vault.auth.secretRef.namespace when using approle auth" $auth.secretRef.namespace | quote }}
            key: {{ required "Set secretStore.provider.vault.auth.secretRef.key when using approle auth" $auth.secretRef.key | quote }}
        {{- else }}
        {{- fail "Unsupported Vault auth method configured for secretStore" }}
        {{- end }}
{{- end }}
