{{- if and .Values.enabled .Values.secretStore.enabled }}
{{- $auth := .Values.secretStore.provider.vault.auth }}
{{- if and $auth.serviceAccountRef.name $auth.serviceAccountRef.namespace }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $auth.serviceAccountRef.name | quote }}
  namespace: {{ $auth.serviceAccountRef.namespace | quote }}
{{- end }}
{{- end }}
