apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nostr-thread-copier.fullname" . }}
  labels:
{{ include "nostr-thread-copier.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "nostr-thread-copier.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "nostr-thread-copier.selectorLabels" . | indent 8 }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
        - name: {{ . }}
{{- end }}
{{- end }}
      serviceAccountName: {{ include "nostr-thread-copier.serviceAccountName" . }}
{{- with .Values.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- with .Values.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.command }}
          command:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.args }}
          args:
{{ toYaml . | indent 12 }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
{{- if .Values.env.extra }}
          env:
{{- range .Values.env.extra }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}
{{- end }}
{{- if .Values.envFrom }}
          envFrom:
{{- range .Values.envFrom }}
            - {{- if .configMapRef }}
              configMapRef:
{{ toYaml .configMapRef | indent 16 }}
              {{- else if .secretRef }}
              secretRef:
{{ toYaml .secretRef | indent 16 }}
              {{- end }}
{{- end }}
{{- end }}
{{- if .Values.livenessProbe.enabled }}
          livenessProbe:
{{ toYaml (omit .Values.livenessProbe "enabled") | indent 12 }}
{{- end }}
{{- if .Values.readinessProbe.enabled }}
          readinessProbe:
{{ toYaml (omit .Values.readinessProbe "enabled") | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      restartPolicy: Always
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
