{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: strfry-egress
spec:
  podSelector:
    matchLabels:
      app: strfry
  policyTypes:
    - Egress
  egress:
    # Allow DNS queries (UDP/TCP 53) to any destination
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- if .Values.networkPolicy.extraCIDRs }}
    - to:
      {{- range $cidr := .Values.networkPolicy.extraCIDRs }}
        - ipBlock:
            cidr: {{ $cidr | quote }}
      {{- end }}
      ports:
      {{- range $p := .Values.networkPolicy.extraPorts }}
        - protocol: {{ default "TCP" $p.protocol }}
          port: {{ $p.port }}
      {{- end }}
    {{- end }}
{{- end }}

