baseDomain: ""

replicaCount: 1
hostPrefix: "relay"

image:
  repository: ghcr.io/paulcapestany/strfry
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 7777
  type: ClusterIP

route:
  # Optional explicit host for the Route (overrides baseDomain/hostPrefix composition)
  host: ""

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

persistence:
  enabled: true
  size: 10Gi
  storageClassName: ""   # empty uses cluster default (hostpath on CRC)

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false

nodeSelector: {}
tolerations: []
affinity: {}

# Optional configuration projected via ConfigMap and mounted at /etc/strfry
config:
  enabled: true
  strfryConf: |
    # Example strfry config (tune as needed)
    [server]
    listen = ":7777"
  routerConf: |
    # Example router config
    [routes]
    # add routing rules here

networkPolicy:
  enabled: false
  # Additional CIDRs to allow egress to (besides DNS 53)
  extraCIDRs: []
  # Additional ports to allow for egress in {port,protocol} objects
  extraPorts: []
