baseDomain: apps-crc.testing

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

persistence:
  size: 10Gi
  storageClassName: ""

config:
  strfryConf: |
    ##
    ## Default strfry config
    ##

    # Directory that contains the strfry LMDB database (restart required)
    db = "./strfry-db/"

    dbParams {
        # Maximum number of threads/processes that can simultaneously have LMDB transactions open (restart required)
        maxreaders = 512

        # Size of mmap() to use when loading LMDB (default is 10TB, does *not* correspond to disk-space used) (restart required)
        mapsize = 10995116277760

        # Disables read-ahead when accessing the LMDB mapping. Reduces IO activity when DB size is larger than RAM. (restart required)
        noReadAhead = true
    }

    events {
        # Maximum size of normalised JSON, in bytes
        maxEventSize = 1048576 # 1 MiB

        # Events newer than this will be rejected
        rejectEventsNewerThanSeconds = 900

        # Events older than this will be rejected
        rejectEventsOlderThanSeconds = 3445948650 # 109 years

        # Ephemeral events older than this will be rejected
        rejectEphemeralEventsOlderThanSeconds = 60 #

        # Ephemeral events will be deleted from the DB when older than this
        ephemeralEventsLifetimeSeconds = 300 #

        # Maximum number of tags allowed
        maxNumTags = 2000

        # Maximum size for tag values, in bytes
        maxTagValSize = 2048
    }

    relay {
        # Interface to listen on. Use 0.0.0.0 to listen on all interfaces (restart required)
        bind = "0.0.0.0"

        # Port to open for the nostr websocket protocol (restart required)
        port = 7777

        # Set OS-limit on maximum number of open files/sockets (if 0, don't attempt to set) (restart required)
        nofiles = 0

        # HTTP header that contains the client's real IP, before reverse proxying (ie x-real-ip) (MUST be all lower-case)
        realIpHeader = "x-forwarded-for"

        info {
            # NIP-11: Name of this server. Short/descriptive (< 30 characters)
            name = "bitiq nostr relay"

            # NIP-11: Detailed information about relay, free-form
            description = "This is a super special strfry instance."

            # NIP-11: Administrative nostr pubkey, for contact purposes
            pubkey = ""

            # NIP-11: Alternative administrative contact (email, website, etc)
            contact = ""
        }

        # Maximum accepted incoming websocket frame size (should be larger than max event) (restart required)
        maxWebsocketPayloadSize = 2097152 # 2 MiB

        # Websocket-level PING message frequency (should be less than any reverse proxy idle timeouts) (restart required)
        autoPingSeconds = 55

        # If TCP keep-alive should be enabled (detect dropped connections to upstream reverse proxy)
        enableTcpKeepalive = true

        # How much uninterrupted CPU time a REQ query should get during its DB scan
        queryTimesliceBudgetMicroseconds = 10000

        # Maximum records that can be returned per filter
        maxFilterLimit = 1000000000000000000

        # Maximum number of subscriptions (concurrent REQs) a connection can have open at any time
        maxSubsPerConnection = 10000

        writePolicy {
            # If non-empty, path to an executable script that implements the writePolicy plugin logic
            plugin = ""
        }

        compression {
            # Use permessage-deflate compression if supported by client. Reduces bandwidth, but slight increase in CPU (restart required)
            enabled = true

            # Maintain a sliding window buffer for each connection. Improves compression, but uses more memory (restart required)
            slidingWindow = true
        }

        logging {
            # Dump all incoming messages
            dumpInAll = false

            # Dump all incoming EVENT messages
            dumpInEvents = false

            # Dump all incoming REQ/CLOSE messages
            dumpInReqs = false

            # Log performance metrics for initial REQ database scans
            dbScanPerf = false

            # Log reason for invalid event rejection? Can be disabled to silence excessive logging
            invalidEvents = false
        }

        numThreads {
            # Ingester threads: route incoming requests, validate events/sigs (restart required)
            ingester = 4

            # reqWorker threads: Handle initial DB scan for events (restart required)
            reqWorker = 4

            # reqMonitor threads: Handle filtering of new events (restart required)
            reqMonitor = 4

            # negentropy threads: Handle negentropy protocol messages (restart required)
            negentropy = 4
        }

        negentropy {
            # Support negentropy protocol messages
            enabled = true

            # Maximum records that sync will process before returning an error
            maxSyncEvents = 1000000000000000000
        }
    }

  routerConf: |
    ## editing this makes live changes
    streams {

      ## Stream down events from our friend relays
      ## https://github.com/hoytech/strfry/blob/master/docs/router.md

      onewaydown {
        dir = "down"
        urls = [
          "wss://offchain.pub"
          "wss://nostr.noones.com"
          "wss://nostr.mom"
          "wss://nostr.oxtr.dev"
          "wss://at.nostrworks.com"
        ]
      }
    #   onewayup {
    #       dir = "up"
    #       filter = {"since":1711402834}
    #        urls = [
    #           "wss://filter.nostr.wine/npub1mznm66caya6rkvpfgj8zy0e83ps2lym44h923ldpkdc4t7scsytqx7ewwy?broadcast=true"
    #       ]
    #   }
    }

networkPolicy:
  enabled: true
  db:
    enabled: true
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: bitiq-local
    ports:
      - port: 8091
        protocol: TCP
      - port: 11210
        protocol: TCP
      - port: 18091
        protocol: TCP
      - port: 18096
        protocol: TCP
  egress:
    additional:
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: openshift-dns
        ports:
          - port: 53
            protocol: UDP
          - port: 53
            protocol: TCP
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
        ports:
          - port: 80
            protocol: TCP
          - port: 443
            protocol: TCP
      - to:
          - ipBlock:
              cidr: ::/0
        ports:
          - port: 80
            protocol: TCP
          - port: 443
            protocol: TCP

# Explicit FQDN for the OpenShift Route
route:
  host: "relay.cyphai.com"
