baseDomain: apps-crc.testing

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

persistence:
  size: 10Gi
  storageClassName: ""

networkPolicy:
  enabled: true
