apiVersion: v2
name: nostr-threads
description: Nostr threads service querying Couchbase for threaded conversations
type: application
version: 0.1.2
appVersion: "0.1.1"
annotations:
  bitiq.io/appversion: "true"
