apiVersion: apps/v1
kind: Deployment
metadata:
  name: nostr-site
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nostr-site
  template:
    metadata:
      labels:
        app: nostr-site
    spec:
      containers:
        - name: web
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
