apiVersion: v1
kind: Service
metadata:
  name: nostr-site
spec:
  selector:
    app: nostr-site
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
