apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: {{ .Values.pipeline.name }}-manual
  namespace: openshift-pipelines
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: main
spec:
  taskRunTemplate:
    serviceAccountName: {{ .Values.pipeline.serviceAccountName }}
    podTemplate:
      securityContext:
        fsGroup: {{ .Values.pipeline.fsGroup }}
  pipelineRef:
    name: {{ .Values.pipeline.name }}
  params:
    - name: git-url
      value: {{ .Values.pipeline.gitUrl }}
    - name: git-revision
      value: {{ .Values.pipeline.gitRevision }}
    - name: runTests
      value: {{ .Values.pipeline.runTests | default "false" | quote }}
    - name: testImage
      value: {{ .Values.pipeline.testImage | default "" | quote }}
    - name: testScript
      value: {{ .Values.pipeline.testScript | default "" | quote }}
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 2Gi
