apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-triggers-eventlistener
subjects:
  - kind: ServiceAccount
    name: {{ .Values.triggers.serviceAccountName | default .Values.serviceAccountName | default "pipeline" }}
    namespace: openshift-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # Grant create of PipelineRuns, events, etc.
  name: tekton-triggers-eventlistener-roles

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-triggers-eventlistener-clusterroles
subjects:
  - kind: ServiceAccount
    name: {{ .Values.triggers.serviceAccountName | default .Values.serviceAccountName | default "pipeline" }}
    namespace: openshift-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # Allow reading ClusterInterceptors and Secrets required by interceptors
  name: tekton-triggers-eventlistener-clusterroles
