{{- if .Values.triggers.create }}
{{- $root := . -}}
{{- $defaultSA := .Values.serviceAccountName | default "pipeline" -}}
{{- $listenerSA := .Values.triggers.serviceAccountName -}}
{{ if .Values.triggers.createSecret }}
{{- $secretKey := $root.Values.triggers.secretKey | default "token" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.triggers.githubSecretName }}
  namespace: openshift-pipelines
type: Opaque
stringData:
  {{ $secretKey }}: {{ required "Set triggers.secretToken when triggers.createSecret=true" .Values.triggers.secretToken | quote }}
{{ end }}

{{ range $idx, $pipeline := .Values.pipelines }}
{{ if $idx }}
---
{{ end }}
{{- $pipelineSA := $pipeline.serviceAccountName | default $defaultSA -}}
{{- $pipelineFsGroup := coalesce $pipeline.fsGroup $root.Values.fsGroup -}}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ $pipeline.name }}-template
  namespace: openshift-pipelines
spec:
  params:
    - name: git-repo-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: {{ $pipeline.name }}-
        namespace: openshift-pipelines
      spec:
        taskRunTemplate:
          serviceAccountName: {{ $pipelineSA }}
{{- if $pipelineFsGroup }}
          podTemplate:
            securityContext:
              fsGroup: {{ $pipelineFsGroup }}
{{- end }}
        pipelineRef:
          name: {{ $pipeline.name }}
        params:
          - name: git-url
            value: $(tt.params.git-repo-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: runTests
            value: {{ $pipeline.runTests | default "false" | quote }}
          - name: testImage
            value: {{ $pipeline.testImage | default "" | quote }}
          - name: testScript
            value: {{ $pipeline.testScript | default "" | quote }}
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 2Gi
{{- end }}

{{- $triggerAccumulator := dict "items" (list) }}
{{- range $idx, $pipeline := .Values.pipelines }}
{{- $events := $pipeline.eventTypes | default (list "push" "pull_request") -}}
{{- $githubSecretKey := $root.Values.triggers.secretKey | default "token" -}}
{{- $githubParams := list
  (dict "name" "secretRef" "value" (dict "secretName" $root.Values.triggers.githubSecretName "secretKey" $githubSecretKey))
  (dict "name" "eventTypes" "value" $events)
}}
{{- $interceptors := list (dict "ref" (dict "name" "github") "params" $githubParams) }}
{{- $filter := "" -}}
{{- if $pipeline.repoFullNames }}
  {{- /* Exact match on repository full_name; include all expected variants in values */ -}}
  {{- $filter = printf "body.repository.full_name in %s" ($pipeline.repoFullNames | toJson) -}}
{{- else if $pipeline.repoFullName }}
  {{- $filter = printf "body.repository.full_name == \"%s\"" $pipeline.repoFullName -}}
{{- end }}
{{- if $filter }}
  {{- $celParams := list (dict "name" "filter" "value" $filter) }}
  {{- $interceptors = append $interceptors (dict "ref" (dict "name" "cel") "params" $celParams) }}
{{- end }}
{{- $triggerName := trimSuffix "-" (trunc 63 (printf "%s-github" $pipeline.name)) }}
{{- $trigger := dict
  "name" $triggerName
  "interceptors" $interceptors
  "bindings" (list (dict "ref" (printf "%s-binding" $pipeline.name)))
  "template" (dict "ref" (printf "%s-template" $pipeline.name))
}}
{{- $_ := set $triggerAccumulator "items" (append (index $triggerAccumulator "items") $trigger) }}
{{- end }}

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ .Values.triggers.eventListenerName }}
  namespace: openshift-pipelines
spec:
{{- if $listenerSA }}
  # If a serviceAccountName is explicitly provided, use it; otherwise allow
  # Tekton Triggers to create and bind an EventListener-specific SA with the
  # required RBAC.
  serviceAccountName: {{ $listenerSA }}
{{- end }}
  triggers: {{ toYaml (index $triggerAccumulator "items") | nindent 4 }}
{{- if .Values.triggers.debugLogging }}
  # Temporary debug logging for troubleshooting. This injects a verbose zap
  # logger config into the EventListener sink container via the supported
  # resources.kubernetesResource Pod spec overlay (Triggers v0.33 on OCP 1.20).
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            containers:
              - env:
                  - name: K_LOGGING_CONFIG
                    value: |
                      {"zap-logger-config":"{\n  \"level\": \"debug\",\n  \"development\": true,\n  \"disableStacktrace\": false,\n  \"sampling\": {\n    \"initial\": 1,\n    \"thereafter\": 1\n  },\n  \"outputPaths\": [\"stdout\"],\n  \"errorOutputPaths\": [\"stderr\"],\n  \"encoding\": \"json\",\n  \"encoderConfig\": {\n    \"timeKey\": \"timestamp\",\n    \"levelKey\": \"severity\",\n    \"nameKey\": \"logger\",\n    \"callerKey\": \"caller\",\n    \"messageKey\": \"message\",\n    \"stacktraceKey\": \"stacktrace\",\n    \"lineEnding\": \"\",\n    \"levelEncoder\": \"\",\n    \"timeEncoder\": \"iso8601\",\n    \"durationEncoder\": \"\",\n    \"callerEncoder\": \"\"\n  }\n}\n"}
{{- end }}

{{ if .Values.triggers.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.triggers.eventListenerName }}
  namespace: openshift-pipelines
spec:
  to:
    kind: Service
    name: el-{{ .Values.triggers.eventListenerName }}
  tls:
    termination: edge
{{ end }}
{{- end }}
