{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-config
data:
  vault.hcl: |
    disable_mlock = true
    ui = true

    storage "raft" {
      path = "/vault/file"
    }

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    api_addr = "http://{{ .Values.service.name }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}"
{{- end }}

