name: Docs Check

on:
  pull_request:
    branches: [ main, master ]

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check required docs
        uses: PaulCapestany/ecosystem/.github/actions/docs-check@main
        with:
          path: .
          files: README.md,AGENTS.md,SPEC.md,TODO.md
